### ISSUE TITLE
error atribute "name" on python 3

### ISSUE THREAD

**Issue by frenyman** [laconicwolf/Nmap-Scan-to-CSV#14]
error python 3.9

```
Traceback (most recent call last):
  File "/opt/scripts/Nmap-XML-to-CSV/xml2csv.py", line 332, in <module>
    main()
  File "/opt/scripts/Nmap-XML-to-CSV/xml2csv.py", line 254, in main
    data = parse_xml(filename)
  File "/opt/scripts/Nmap-XML-to-CSV/xml2csv.py", line 118, in parse_xml
    scan_data = get_host_data(root)
  File "/opt/scripts/Nmap-XML-to-CSV/xml2csv.py", line 74, in get_host_data
    service = port.findall('service')[0].attrib['name']
KeyError: 'name'
```

**Comment by jose-devcode** [comment]
I have this same issue

**Comment by bsdshneg** [comment]
me too

Solution:
service = port.findall('service')[0].attrib.get('name', 'unknown')
